### ISSUE TITLE
Autofilling on request withdraw on chrome

### ISSUE THREAD

**Issue by rakeshok** [moneypot/bustabit-webserver#227] opened 2015-07-14 00:18 UTC
Chrome adds your username on the input above a password input no matter what, this is one way to fix it

http://stackoverflow.com/questions/15738259/disabling-chrome-autofill

**Comment by kungfuant** [comment] 2015-07-14 18:54
Duplicate of #101

**Closed** 2015-08-12 19:13 UTC
Labels: low-priority
